name: Uptime Bot
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Config Git
        run: |
          git config --global user.name "PkLavc"
          git config --global user.email "patrickajm@gmail.com"

      - name: Random Start Delay
        run: |
          DELAY=$(( ( RANDOM % 903 ) + 2700 ))
          sleep $DELAY

      - name: Run Check
        run: |
          git reset --hard HEAD
          python monitor.py
        
      - name: Random Commit Delay
        run: |
          DELAY=$(( ( RANDOM % 120 ) + 300 ))
          sleep $DELAY

      - name: Auto PR and Merge
        env:
          GH_TOKEN: ${{ secrets.PAT_SHARK }}
        run: |
          git add .
          git stash || true
          git pull --rebase origin main -X ours
          git stash pop || true
          
          bash workflow.sh
